dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

git:
  depth: 1

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules
    - ./projects/angular-5-test/node_modules
    - ./projects/angular-6-test/node_modules
    - ./projects/angular-7-test/node_modules
    - ./projects/angular-8-test/node_modules
    - ./dist/ngx-autofocus-fix # for persistence between stages

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests & Linter"
      install: npm install
      script:
        - npm run lint
        - npm run test:ci
    - stage: "Build"
      name: "Making production build"
      script: npm run build
    - stage: "E2e"
      name: "E2E Tests"
      install: npm run e2e-install
      script: npm run e2e:prod
    - stage: "Version"
      name: "Prepare Version"
      script: npm run prepare-ver
#    - stage: "publish"
#      name: "Publishing the package"

stages:
  - Tests
  - Build
  - E2e
  - Version
