# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - lib-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - lib-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run lint
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run tests
          command: npm run test:ci

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build package
          command: npm run build

      - persist_to_workspace:
          root: ~/repo
          paths: .

  e2e:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
            - e2e-dependencies-ng5-{{ checksum "projects/angular-5-test/package.json" }}
            - e2e-dependencies-ng5-

      - restore_cache:
          keys:
            - e2e-dependencies-ng8-{{ checksum "projects/angular-6-test/package.json" }}
            - e2e-dependencies-ng6-

      - restore_cache:
          keys:
            - e2e-dependencies-ng7-{{ checksum "projects/angular-7-test/package.json" }}
            - e2e-dependencies-ng7-

      - restore_cache:
          keys:
            - e2e-dependencies-ng8-{{ checksum "projects/angular-8-test/package.json" }}
            - e2e-dependencies-ng8-

      - run:
          name: Install E2E dependencies
          command: npm run e2e-install

      - save_cache:
          paths:
            - projects/angular-5-test/node_modules
          key: e2e-dependencies-ng5-{{ checksum "projects/angular-5-test/package.json" }}

      - save_cache:
          paths:
            - projects/angular-6-test/node_modules
          key: e2e-dependencies-ng6-{{ checksum "projects/angular-6-test/package.json" }}

      - save_cache:
          paths:
            - projects/angular-7-test/node_modules
          key: e2e-dependencies-ng7-{{ checksum "projects/angular-7-test/package.json" }}

      - save_cache:
          paths:
            - projects/angular-8-test/node_modules
          key: e2e-dependencies-ng8-{{ checksum "projects/angular-8-test/package.json" }}

      - run:
          name: Run E2E tests
          command: npm run e2e

#  deploy-dev:
#    <<: *defaults
#    steps:
#      - attach_workspace:
#          at: ~/repo
#      - run:
#          name: Authenticate with registry
#          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
#      - run:
#          name: Publish package
#          command: npm run publish:dev
#
#  deploy-prod:
#    <<: *defaults
#    steps:
#      - attach_workspace:
#          at: ~/repo
#      - run:
#          name: Authenticate with registry
#          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
#      - run:
#          name: Publish package
#          command: npm run publish:prod

workflows:
  version: 2
  test-deploy:
    jobs:
#      - test:
#          filters:
#            tags:
#              only: /^v.*/
      - install:
          filters:
            branches:
              only: /master/
      - lint:
          requires:
              - install
          filters:
            branches:
              only: /master/
      - test:
          requires:
              - install
          filters:
            branches:
              only: /master/
      - build:
          requires:
            - install
            - lint
            - test
          filters:
            branches:
              only: /master/
      - e2e:
          requires:
            - build
          filters:
            branches:
              only: /master/

#      - deploy-dev:
#          requires:
#            - test
#            - build
#          filters:
#            branches:
#              only: /develop/
#      - deploy-prod:
#          requires:
#            - test
#            - build
#          filters:
##            tags:
##              only: /^v.*/
#            branches:
#              only: /master/
